"""empty message

Revision ID: 9d864dd7754c
Revises: 009f39a1a5d2
Create Date: 2026-01-05 12:39:25.867044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d864dd7754c'
down_revision: Union[str, None] = '009f39a1a5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timestamp columns with server defaults for existing tables
    op.add_column('order', sa.Column('createdAt', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('order', sa.Column('updatedAt', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    op.add_column('user', sa.Column('createdAt', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user', sa.Column('updatedAt', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    op.add_column('user_orders', sa.Column('createdAt', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user_orders', sa.Column('updatedAt', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'updatedAt')
    op.drop_column('user_orders', 'createdAt')
    op.drop_column('user', 'updatedAt')
    op.drop_column('user', 'createdAt')
    op.drop_column('order', 'updatedAt')
    op.drop_column('order', 'createdAt')
    # ### end Alembic commands ###