"""empty message

Revision ID: 461546ee29be
Revises: ce0b5ecbfb6f
Create Date: 2026-01-05 10:09:02.046397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461546ee29be'
down_revision: Union[str, None] = 'ce0b5ecbfb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('OrderId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrderId'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserId', 'OrderId', name='uq_user_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_orders')
    # ### end Alembic commands ###